[package]
name = "dota2-timer"
version = "0.1.0"
edition = "2024"


[dependencies]
native-windows-gui = "1.0.12"
winapi = "0.3.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
embed-resource = "3.0"
